### ISSUE TITLE
download_resources.sh fails to download gluster server

### ISSUE THREAD

**Issue by awest1339** [jfeild1337/multiscanner-ansible#9]
* https://github.com/jfeild1337/multiscanner-ansible/blob/master/download_resources.sh#L49
* Is this line supposed to be just "glusterfs" instead of "glusterfs-server"?
* The latest version of glusterfs I see in the yum repo is 3.7.9, not 3.10.0. Did you enable an extra repo to download the latest?

**Comment by jfeild1337** [comment]
Fixed by https://github.com/jfeild1337/multiscanner-ansible/commit/7a967e5f86138e966ed3dbac298af5fba1b05874, https://github.com/jfeild1337/multiscanner-ansible/commit/b0d520384afcaea36d26994cae1e1b6639988c39, and https://github.com/jfeild1337/multiscanner-ansible/commit/d124547e532ed5e62d2f22dc8a74a962449e7916.
Thanks @awest1339!
